### ISSUE TITLE
ThumbnailnatorProgressiveAlgorithm.resize - alternative algorithm that may be interesting (not an issue)

### ISSUE THREAD

**Issue by Andrew-Cottrell** [patrickfav/density-converter#43]
Some years ago, I wrote a progressive bilinear resize that is similar to the [`ThumbnailnatorProgressiveAlgorithm.resize`](https://github.com/patrickfav/density-converter/blob/v1.0.0-alpha9/src/main/java/at/favre/tools/dconvert/converters/scaling/ThumbnailnatorProgressiveAlgorithm.java#L63) method. I thought people might be interested in the algorithm I developed for image down-scaling.

```java
    private static final double RECIPROCAL_LOG_SCALE_FACTOR = -1 / Math.log(2.0d);

    @Test
    public void testProgressiveResizeAlgorithm() {

        /* The target width:height should have the same aspect ratio as scrImage. */
        final int targetWidth = 80;
        final int targetHeight = 45;

        int currentWidth  = 1920; // srcImage.getWidth();
        int currentHeight = 1080; // srcImage.getHeight();

        while (currentWidth != targetWidth) {
            final double logarithm  = Math.log((double)currentWidth / (double)targetWidth);
            final double scaleFactor = Math.exp(logarithm / Math.floor(logarithm * RECIPROCAL_LOG_SCALE_FACTOR));
            currentWidth = Math.max(targetWidth, (int)Math.round(currentWidth * scaleFactor));
            currentHeight = Math.max(targetHeight, (int)Math.round(currentHeight * scaleFactor));
            System.out.println(
                    "Scale factor: " + scaleFactor +
                    ", width: " + currentWidth +
                    ", height: " + currentHeight);
            // g.drawImage(tempImage, 0, 0, currentWidth, currentHeight, ...
        }

        Assert.assertEquals(targetWidth, currentWidth);
    }
```

```
Scale factor: 0.5296119205244061, width: 1017, height: 572
Scale factor: 0.5295930273405994, width: 539, height: 303
Scale factor: 0.529460713543599, width: 285, height: 160
Scale factor: 0.5298129428260175, width: 151, height: 85
Scale factor: 0.5298013245033113, width: 80, height: 45
```

It does exactly the same number of scaling operations that would be done if we simply used a scale factor of 0.5 for each iteration except for the last iteration. But, rather than use a scale factor of 0.5 for each iteration, it calculates a scale factor, that will be 0.5 or greater, so that a similar scale factor is used for each iteration, including the last iteration. The idea is to avoid undershooting the target size or having a last iteration with a scale factor closer to 1.

For the example above (1920×1080 -> 80×45) with the halving algorithm, either the width would undershoot to 60px or the last iteration would use a scale factor of two-thirds (0.6666...).

For 1920×1080 -> 400×225, the halving algorithm would undershoot the width to 240px or use a scale factor of 0.8333... on the last iteration. The alternative algorithm instead scales by a factor of approximately 0.593 on each iteration.

```
Scale factor: 0.5928155507483438, width: 1138, height: 640
Scale factor: 0.5928691667287522, width: 675, height: 379
Scale factor: 0.5925925925925926, width: 400, height: 225
```

Feel free to close this issue, which is not really an issue as I'm not making an actionable suggestion here.

**Comment by Andrew-Cottrell** [comment]
Closing this as it wasn't an issue and I didn't make any actionable suggestion. Sorry for wasting anyone's time. I think I just got a bit carried away and didn't think it through.

**Comment by patrickfav** [comment]
Hey @Andrew-Cottrell thanks for input! To be fair, this project is a bit old and not very well maintained by me, so reactions to it are a bit delayed and I'm not to deep in the subject matter anymore.

Please don't apologize, I think your idea of adapting the steps totally makes sense and thanks for sharing! Keep up the creativitiy and keep sharing your ideas!

Cheers!
