### ISSUE TITLE
Problems while building with mvnw

### ISSUE THREAD

**Issue by MaxiCode** [patrickfav/density-converter#5]
I would like to build the `density-converter` with: `./mvnw clean package`.
But i get some error with javafx. See attached file.
Hope you can help me.
[mvnw_error.log](https://github.com/patrickfav/density-converter/files/3297202/mvnw_error.log)

**Comment by MaxiCode** [comment]
Hi again,
solve this issue. Fortunately, it has nothing to do with your project. I'm using arch `uname -a` results in `Linux darwin 4.20.17-1-MANJARO #1 SMP PREEMPT Tue Mar 19 18:07:36 UTC 2019 x86_64 GNU/Linux`. 
Java 8 openjdk comes without `java-openjfx`.
Installing this package solved this issue in my case: `pacman -S java-openjfx`.

**Comment by patrickfav** [comment]
Glad you solved this. Any suggestions on to avoid this for others (readme etc.?)
